apiVersion: v1
kind: Template
metadata:
  name: heatdrill-template
  annotations:
    openshift.io/display-name: "All components for AGI Heatdrill Service"
    description: >-
      "Creates all necessary components for the AGI Heatdrill Service"
    openshift.io/long-description: >-
      "Creates all necessary components for the AGI Heatdrill Service"
    tags: "agi,gdi,heatdrill,java"
    iconClass: icon-java
labels:
  env: ${env}
  createdBy: heatdrill-template
parameters:
  - description: DB Server
    name: DB_SERVER
    value:
  - description: DB Passwort
    name: DB_PW
    value:
  - description: Name for Environment
    name: env
    required: true
    value: test
  - description: Version of Image
    name: version
    required: true
    value:
  - description: Scheduled "true/false"
    name: scheduled
    required: true
    value: "false"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: heatdrill
    application: heatdrill-${env}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/heatdrill:${version}
      importPolicy:
        scheduled: ${{scheduled}}
      name: ${version}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: template-heatdrill
      description: Deployment Config for heatdrill-service Pod
    creationTimestamp: null
    generation: 1
    labels:
      application: heatdrill-${env}
    name: heatdrill-${env}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: heatdrill-${env}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 60
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: template-heatdrill
        creationTimestamp: null
        labels:
          application: heatdrill-${env}
          deploymentconfig: heatdrill-${env}
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: >-
              {"db-connection":{"url":"jdbc:postgresql://${DB_SERVER}:5432/sogis","userName":"mswrite","password":"${DB_PW}"}}
          image: sogis/heatdrill
          imagePullPolicy: IfNotPresent
          name: heatdrill-${env}
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - heatdrill-${env}
        from:
          kind: ImageStreamTag
          name: heatdrill:${version}
          namespace: agi-heatdrill
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: heatdrill-service-${env}
    annotations:
      description: http port of application
    labels: 
      application: heatdrill-${env}
  spec:
    selector:
      deploymentconfig: heatdrill-${env}
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: "80"

