apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ilivalidator-template
  annotations:
    openshift.io/display-name: "All components for AGI Ilivalidator Web Service"
    description: >-
      "Creates all necessary components for the AGI Ilivalidator Web Service"
    openshift.io/long-description: >-
      "Creates all necessary components for the AGI Ilivalidator Web Service"
    tags: "agi,gdi,ilivalidator,java"
    iconClass: icon-java
labels:
  application: Ilivalidator
  createdBy: ilivalidator-template
parameters:
  - description: Name for Environment
    name: env
    value: test
  - description: Version of Image
    name: version
    value:
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Image Stream of the application
    labels:
      application: ilivalidator-web-service  
    creationTimestamp: null
    generation: 1
    name: ilivalidator-web-service
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      application: ilivalidator-web-service
      deploymentconfig: ilivalidator-web-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: ilivalidator-web-service
          deploymentconfig: ilivalidator-web-service
      spec:
        containers:
        - image: sogis/ilivalidator-web-service
          imagePullPolicy: IfNotPresent
          name: ilivalidator-web-service
          ports:
          - containerPort: 8888
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: ilivalidator-web-service-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: ilivalidator-web-service-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ilivalidator-web-service
        from:
          kind: ImageStreamTag
          name: ilivalidator-web-service:${version}
          namespace: agi-ilivalidator-web-service-${env}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    name: ilivalidator-service
    annotations:
      description: http port of application
    labels:
      application: ilivalidator-web-service
  spec:
    selector:
      application: ilivalidator-web-service
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8888
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ilivalidator-web-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/ilivalidator-web-service:${version}
      name: ${version}
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 1200s
    labels:
      application: Ilivalidator
      createdBy: ilivalidator-template
    name: ilivalidator-${env}
    namespace: agi-ilivalidator-web-service-${env}
  spec:
    host: ilivalidator-${env}.dev.so.ch
    port:
      targetPort: "80"
    to:
      kind: Service
      name: ilivalidator-service
      weight: 100
    wildcardPolicy: None
