apiVersion: v1
kind: Template
metadata:
  name: create-pvcs-template
labels:
  app: pgwatch
parameters:
- desription: pgwatch environment (test|production)
  name: ENV
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pw2-influxdb-${ENV}-claim
    labels:
      app: pgwatch
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pw2-pgwatch-${ENV}-claim
    labels:
      app: pgwatch
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pw2-postgresql-${ENV}-claim
    labels:
      app: pgwatch
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: nfs
