apiVersion: v1
data:
  my.cnf: |
    [mysqld]

    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links = 0

    # http://www.percona.com/blog/2008/05/31/dns-achilles-heel-mysql-installation/
    skip_name_resolve

    # http://www.chriscalender.com/ignoring-the-lostfound-directory-in-your-datadir/
    ignore-db-dirs=lost+found

    # GlusterFS equivalent of 'lost+found'
    ignore-db-dirs=.trashcan

    # Snapshot
    ignore-db-dirs=.snapshot

    !includedir /etc/my.cnf.d
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-cnf
  selfLink: /api/v1/namespaces/agi-infrastructure-integration/configmaps/mysql-cnf
