apiVersion: v1
kind: Template
metadata:
  name: create-persistent-volumes
  annotations:
    description: >-
      "Creates persistent volumes for web gis client and api"
parameters:
  - description: Environment
    name: env
    value: test
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: qwc-assets-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2GiB
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: jasper-config-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1GiB
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: nginx-config-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1GiB
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: qgs-resources-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5GiB
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: reports-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5GiB
    storageClassName: nfs
