apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: qwc-assets-claim
  selfLink: /api/v1/namespaces/gdi-test/persistentvolumeclaims/qwc-assets-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: netapp
  volumeName: netapp-gditest-qwc-assets
status: {}
